version: "3.7"

services:
    server:
        container_name: tap-server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "6789:6789"
            
    client:
        container_name: tap-client
        build:
          context: ./client
          dockerfile: Dockerfile
          
        volumes:
          - ./client:/app
          - node_modules:/client/node_modules
        ports:
          - "3000:3000"
        depends_on:
          - server